### ISSUE TITLE
Wrong patch format in find.b445af98(find13)-OTcyZjg1Mz's patch

### ISSUE THREAD

**Issue by Ultimanecat** [dbgbench/dbgbench.github.io#1]
I got the following when trying to apply the patches:
Cannot apply OTcyZjg1Mz's patch to find.b445af98 (find13).
It seems that the patch file has a broken header.

**Comment by mboehme** [comment]
Correct. The header is broken. Can you fix it and submit a pull request?

The header should look something like this
```
diff --git a/find/pred.c b/find/pred.c
index 27db863..eea102d 100644
--- a/find/pred.c
+++ b/find/pred.c
@@ -1723,7 +1723,11 @@ pred_type (const char *pathname, struct stat *stat_buf, struct predicate *pred_ptr)
```

**Comment by mboehme** [comment]
Thanks @Ultimanecat!
